"""Edit Days model

Revision ID: b4a7c2ef794e
Revises: 1848fd80d6a5
Create Date: 2021-04-12 15:02:38.102126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4a7c2ef794e'
down_revision = '1848fd80d6a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('days', sa.Column('iftorlik', sa.DateTime(), nullable=True))
    op.add_column('days', sa.Column('saharlik', sa.DateTime(), nullable=True))
    op.drop_column('days', 'time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('days', sa.Column('time', sa.DATETIME(), nullable=True))
    op.drop_column('days', 'saharlik')
    op.drop_column('days', 'iftorlik')
    # ### end Alembic commands ###
